-- 1. Find the total revenue generated. --

USE ecom;

SELECT SUM(quantity * price_per_unit) AS total_revenue
FROM orders;

-- 2. Find the total quantity of products sold.--

SELECT SUM(quantity) AS total_quantity
FROM orders;

-- 3. Find the total revenue generated by each category.

SELECT SUM(quantity * price_per_unit) AS total_revenue_each_category,category
FROM orders
GROUP BY category ;

-- 4. Find the total revenue generated by each city.

SELECT city,SUM(quantity * price_per_unit) AS total_revenue_city_wise
FROM orders
GROUP BY city ;

-- 5. Find the total quantity sold by each payment mode.

SELECT payment_mode,SUM(quantity) AS total_quantity_payment_mode_wise
FROM orders
GROUP BY payment_mode;

-- 6. Find the total revenue from delivered orders only.

SELECT SUM(quantity * price_per_unit) AS total_revenue_of_delivered_ordered
FROM orders
WHERE order_status = 'Delivered';

-- 7. Find the total quantity sold for Electronics category.

SELECT SUM(quantity) AS quantity_electronics
FROM orders
WHERE category = 'Electronics';

-- 8. Find the total revenue generated by each customer.

SELECT customer_name,SUM(quantity * price_per_unit) AS total_revenue_of_customers
FROM orders
GROUP BY customer_name ORDER BY total_revenue_of_customers DESC ;

-- 9. Find the delivery partner who delivered the highest quantity of products.

SELECT delivery_partner,
       SUM(quantity) AS total_quantity
FROM orders
GROUP BY delivery_partner
ORDER BY total_quantity DESC;

-- 10. Find monthly revenue.

SELECT MONTH(order_date) AS month,
SUM(quantity * price_per_unit) AS revenue
FROM orders
GROUP BY month;

-- FOR MONTH NAME

SELECT MONTHNAME(order_date) AS month,
SUM(quantity * price_per_unit) AS revenue
FROM orders
GROUP BY month;