-- ii) IF WE DELETE THE RECORD THE WHOLE ROW NOT BEEN DELETED JUST THE INDIVIUAL RECORD OF FOREIGN KEY BECOMES NULL INSTEAD OF
-- DELETING THE WHOLE ROW

ALTER TABLE department
DROP FOREIGN KEY fk_department;

ALTER TABLE department
ADD CONSTRAINT fk_department
FOREIGN KEY(emp_id) REFERENCES employees(emp_id)
ON DELETE SET NULL;

SELECT * FROM employees;

INSERT INTO department VALUES('cs',1,1),('ca',2,2);

DELETE FROM employees
WHERE emp_id = 2;

SELECT * FROM employees;